export const itemes = [
  {
    id: "c1a70e871ca33984f0ec1567ff753421",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./html3/source/Img/KarenDarbinyan.jpg",
  },
  {
    id: "eddca6089f65c99be2498a45af312607",
    firstName: "Alexandr",
    lastName: "Hambardzumyan",
    phone: "+374 93 11 44 15",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "RELQ school",
    imagePath: "./html3/source/Img/AlexandrHambardzumyan.jpg",
  },
  {
    id: "bf2ee095abe0c7ece0dc4c6350986525",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "+374 44 14 80 00",
    email: "Khechumyan63@gmail.com",
    education: "Yerevan State University",
    workExperience: "School Principal-School N67 Bitschool",
    trainings: "RELQ",
    imagePath: "./html3/source/Img/AnahitKhechumyan.jpg",
  },
  {
    id: "a5be3c14b3aa8b748396c7411feaa83b",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "+374 41 90 08 02",
    email: "antonyanani30@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "RELQ",
    imagePath: "./html3/source/Img/AniAntonyan.jpg",
  },
  {
    id: "b1656bc0de2c4cbcabc72174e8160717",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "+374 98 14 44 50",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./html3/source/Img/AnnaHayriyan.jpg",
  },
  {
    id: "a7a519f05dcb5602d2fac8d84003f776",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "+374 94 90 21 71",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/ArmenakQocharyan.jpg",
  },
  {
    id: "a187018154befe0cb847ac25eac5ffe1",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "+374 55 90 01 55",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./html3/source/Img/ArusyakAghajanyan.jpg",
  },
  {
    id: "adf2672fc005a5f894859c740047fe85",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "+374 96 33 33 28",
    email: "afina.panyan00@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq",
    imagePath: "./html3/source/Img/AfinaPanyan.jpg",
  },
  {
    id: "d21359f708de605fd34a47fce31708a8",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "+374 93 28 55 95",
    email: "tadevosyanbabken906@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq",
    imagePath: "./html3/source/Img/BabkenTadevosyan.jpg",
  },
  {
    id: "cd871498a405c14c9e39e3d6c952b642",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "+374 99 46 36 23",
    email: "gevorgyan.icml@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq",
    imagePath: "./html3/source/Img/HasmikGevorgyan.jpg",
  },
  {
    id: "a50359439356774ee83f1bf23468f5b1",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "+374 43 26 65 99",
    email: "melkumyanhermine@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq",
    imagePath: "./html3/source/Img/HermineMelkumyan.jpg",
  },
  {
    id: "c1f6cb03b0b3cd3eebceea0ec885db8a",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "+374 97 14 44 50",
    email: "hermine.sahakyan33@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq",
    imagePath: "./html3/source/Img/HermineSahakyan.jpg",
  },
  {
    id: "c7f171ba8706b07eb4582ab368c6548e",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "+374 97 75 95 99",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./html3/source/Img/LarineDanielyan.jpg",
  },
  {
    id: "e1b354f875865cb1a7d71d39e84bc934",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "+374 91 55 53 74",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./html3/source/Img/LianaDashyan.jpg",
  },
  {
    id: "9b2ad70b0d72ce1ccecd9b04a6a5e82e",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "+374 43 18 18 34",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "./html3/source/Img/LusineYeremyan.jpg",
  },
  {
    id: "a594ac2d4ca3f0a4d8b9303cbed30162",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "+374 93 32 29 02",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "Junior Accountant",
    trainings: "Relq",
    imagePath: "./html3/source/Img/LusinePetrosyan.jpg",
  },
  {
    id: "faa1585c9d72354995eb963606d47b25",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "+374 44 05 51 50",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/MaratHarutyunyan.jpg",
  },
  {
    id: "b61eea13ce401b07a6696ec7baa98449",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "+374 94 27 67 00",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/NarekTovmasyan.jpg",
  },
  {
    id: "b4d19267b34a348fb2268b4fb01fec7f",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "+374 98 31 38 71",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "Junior Accountant",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "./html3/source/Img/SedaShahnazaryan.jpg",
  },
  {
    id: "9c148e3d5a80b78eff0cc6b20b741d10",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "+374 94 24 68 80",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "Junior Accountant",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/SeryozhaAsatryan.jpg",
  },
  {
    id: "9d089f09e0ea7228d4f5d92daa7bf676",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "+374 77 12 16 96",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "Junior Accountant",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/SevakStepanyan.jpg",
  },
  {
    id: "9f486d39f0c1b20a8ca0635451efd6f0",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "+374 98 20 02 72",
    email: "silvaohanyan90@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/SilvaOhanyan.jpg",
  },
  {
    id: "b6f523880ba41b7a96603d5b84d4c4ae",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "+374 77 76 09 86",
    email: "galstyan.suren.1986@gmail.com",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/SurenGalstyan.jpg",
  },
  {
    id: "82d22532715fd22efe9a4530de4e4c4b",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "+374 77 15 18 68",
    email: "martirosyant01@mail.ru",
    education: "programmer",
    workExperience: "Junior Accountant",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/TigranMartirosyan.jpg",
  },
  {
    id: "a86057ded26a345f902fbe506b85af78",
    firstName: "Narine",
    lastName: "Avetisyan",
    phone: "+374 93 27 91 90",
    email: "avetisyannarine@gmail.com",
    education: "programmer",
    workExperience: "Frontend Specialist ",
    trainings: "Relq School",
    imagePath: "./html3/source/Img/NarineAvetisyan.jpg",
  },
];
